name: release
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.3
  http: ^1.2.2
  flutter_spinkit: ^5.2.1
  ua_client_hints: ^1.4.0
  provider: ^6.1.2
  url_launcher: ^6.3.1
  flutter_svg: ^2.0.16
  photo_view: ^0.15.0
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  mask_text_input_formatter: ^2.9.0
  internet_connection_checker: ^1.0.0+1
  firebase_messaging: ^15.1.6
  firebase_core: ^3.8.1


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0




flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
